### ISSUE TITLE
功能建议 希望在词汇标签旁加个复制按钮，可方便的单独复制

### ISSUE THREAD

**Issue by SF-NX** [KonghaYao/ai-tag#1]
感谢

**Comment by KonghaYao** [comment]
但是我考虑到移动端位置不够了，所以没有设计单独的复制，这个实现不难，但是位置上确实不太好弄🙂

**Comment by SF-NX** [comment]
这样可行吗
![20221023111752](https://user-images.githubusercontent.com/89298437/197371663-ae1e0a03-c536-4fcd-bcfb-7f817b4a2bac.png)

**Comment by KonghaYao** [comment]
不行啊，移动端很容易误触，太小了不行，太大了占空间

**Comment by SF-NX** [comment]
那直接双击复制可以吗🤧 再加个逗号

**Comment by KonghaYao** [comment]
但是移动端没有双击，太惨了

**Comment by SF-NX** [comment]
先把电脑端整上吧 
![601a9798-77f7-44cb-bbc7-df9165513dd2](https://user-images.githubusercontent.com/89298437/197376990-8af7eafa-5160-4d6b-ba4c-08b6bb89bbaf.jpg)

**Comment by KonghaYao** [comment]
行，下个小版本给上

**Comment by KonghaYao** [comment]
ok，完成了，现在双击任何一个标签都是复制了，但是移动端应该不行，没有提示是因为后面看看有什么更好的方式吧，这个双击行为冲突有点大

**Comment by SF-NX** [comment]
谢谢好兄弟
![image](https://user-imag.githubusercontent.com/89298437/197378357-6f1c86f3-fd5b-470e-902e-af1289cde0f8.png)

**Comment by KonghaYao** [comment]
感谢支持，帮我多多宣传一下吧👍

**Comment by SF-NX** [comment]
那必须
