### ISSUE TITLE
支援中文的貪婪搜尋

### ISSUE THREAD

**Issue by bluelovers** [KonghaYao/ai-tag#167]
支援中文的貪婪搜尋
來達到不論是輸入繁體 簡體 日文漢字 都能搜尋

https://github.com/bluelovers/ws-regexp/tree/master/packages/regexp-cjk-with-plugin-enabled

**Comment by KonghaYao** [comment]
魔导绪论使用的搜索方式是 全文搜索，使用了一个叫 fuse.js 的插件，理论上是可以实现多种语言的搜索的😄。

**Comment by bluelovers** [comment]
> 魔导绪论使用的搜索方式是 全文搜索，使用了一个叫 fuse.js 的插件，理论上是可以实现多种语言的搜索的😄。

我用繁體搜尋時 無法搜到簡體項目

**Comment by bluelovers** [comment]
我給的網址裡面能做到這些

![image](https://user-images.githubusercontent.com/167966/223804067-e5fa0f45-8a97-4268-8b56-4baba0f1a8bf.png)

**Comment by KonghaYao** [comment]
![image](https://user-images.githubusercontent.com/68177907/223870133-e1c67057-18d1-442c-8e05-d96a530528de.png)

已解决繁体搜索问题😄，估计在下午就能看到了
