### ISSUE TITLE
支援表情符號

### ISSUE THREAD

**Issue by bluelovers** [KonghaYao/ai-tag#168]
https://wolfchen.top/tag/

![image](https://user-images.githubusercontent.com/167966/223360921-d261d152-9d08-4141-a105-9d6089bd6287.png)

![image](https://user-images.githubusercontent.com/167966/223360974-9114d974-5f1d-43ef-a416-45dd1fe7bd0d.png)

**Comment by KonghaYao** [comment]
我以前看到过有一个收集 emoji 的网站，里面对 emoji 进行了英文的注释，如果加入搜索的话，这个可能比较合适。总之，会列入下个 feat 的，谢谢您的建议😄

**Comment by bluelovers** [comment]
試試 emoji.json
