### ISSUE TITLE
【翻译功能】我建立了一个tags的翻译项目，希望能够帮助你们进行翻译

### ISSUE THREAD

**Issue by zhongpei** [KonghaYao/ai-tag#179]
https://github.com/zhongpei/stable-diffusion-tags-translate

原理是读取预设的人工整理的txt或csv，然后通过google api翻译剩下没有整理过的。最后在人工校对google翻译的部分，整理到csv里面。这样项目就可以定期翻译一批整理一批。

**Comment by KonghaYao** [comment]
您好，我们这边把所有的 Tag 都放置到我们的搜索服务器上了，所以提供了快速的全文搜索服务搜索词汇，我们将会尝试合并您的数据，感谢您的贡献。
由于现阶段我们对于 Tag 和 Prompt 的考量，认为人力统计 Tag 确实困难，并且 AI 和人、人和人之间对于 Tag 的理解都差太远，导致在写 Prompt 的时候总是不知道写那种好，并且花费时间成本太高。
而我们的最终目标是提供一个 AI 会话所需要的 Prompt，是一个文段，那么 ChatGPT 优势很大，通过 Context 构建可以实现高效的文本生成，这点在我们网站已有实践证明。当然，在国内相关政策出台之后，ChatGPT 功能被封禁的可能非常大，这也是我们的忧虑。
所以，我们对于 Prompt 的最终方案是 `文段意义化+GPT生成+Tag辅助修正`，这一套在使用效率上达到了较为良好的效果。

**Comment by zhongpei** [comment]
感谢分享你们项目的经验；我也尝试用模型来做Prompt的生成，目前实现了本地ChatGLM+Prompt优化模型，计划通过炼T5模型的方式来优化Prompt；希望本地模型也能达到ChatGPT类似的效果。
