### ISSUE TITLE
魔导绪论Ai魔咒助手报错获取失败

### ISSUE THREAD

**Issue by 1216115881** [KonghaYao/ai-tag#186]
Token是自己在官网买的GPT4，而后在
https://chat.openai.com/api/auth/session
上获取的，依旧提示获取失败
![8e17b91e1b833e4a4543b6aa53194d1](https://github.com/KonghaYao/ai-tag/assets/160310498/6fcfd5f3-ae21-425b-a0e0-79fdc2669116)
![1bd4cad5e942a02e245430e6fe240a9](https://github.com/KonghaYao/ai-tag/assets/160310498/7a7cf085-7986-445b-b166-0d870f76a43b)

**Comment by KonghaYao** [comment]
我记得我当年写的模型是 3.5 的模型，那时候没有 4 嘞 @1216115881

**Comment by 1216115881** [comment]
那应该如何使用ai魔咒助手，我第一次购买GPT4，我在Chat切换模型并不会改变Token，ai魔咒助手依旧报错Failed to fetch @KonghaYao

**Comment by KonghaYao** [comment]
唔，我看了一下 openai 他们下架了以前那个模型，我只能改为 3.5 但是没有 token 了，要等一会发个版本 @1216115881

**Comment by KonghaYao** [comment]
抱歉让你久等了，发完版本了，用了别人的 3.5 转接测试了一下，暂时没有问题 @1216115881

**Comment by 1216115881** [comment]
非常感谢 @KonghaYao
