### ISSUE TITLE
关于许可证的建议

### ISSUE THREAD

**Issue by shigma** [KonghaYao/ai-tag#8]
作者您好，我慕名而来，看到你的项目底部是这样声明的：

> GPL 3.0
> 注意啦，不允许商用

这里你可能需要注意一下：[GPLv3 和其他大部分主流协议](https://choosealicense.com/licenses/) 都没有禁止商用的条款，因此你只要使用了这些协议，**即使声明不允许商用也是无效的**。如果想要禁止商用，需要使用专门的协议，比如 SSPL 或者 CC-NC 等 (尽管我举出的两个例子都不太适用你的项目)，又或者自行拟定全部的协议文本 (可以以 GPL 等现有协议文本为基础修改，但你需要考虑协议自身没有漏洞)。当然，最简单的方法是把「不允许」修改为不具备效力的「作者不建议商用」。

我本人没有其他意思，只是不希望见到你的项目因为相关法律知识的缺失而做了别人的嫁衣。祝好。

如果觉得没必要修改可以直接关闭此 issue。

**Comment by KonghaYao** [comment]
感谢您的反馈，嘿嘿嘿，看来是我理解错了，我改为了不建议商用，在此感谢您的友好提示。

送您一张漂亮的 AI 图

![{{{masterpiece}}},{{highly detailed}},{{{best quality}}},{{{full body}}},{{{flower field}}},starry sky,1girl,detailed flower face,{{milkpanda}},{{dynamic pose}},solo,blue hair,long s-546737721 (1)](https://user-images.githubusercontent.com/68177907/198879101-d64e28fb-7c2f-4c0f-aa82-f0fc4cdcda9c.png)
